---
- name: Reset the MOTD back to the default
  hosts: rpis
  tasks:
    - ping:
    - name: Reset the MOTD back to the factory default
      ansible.builtin.template:
        src: ./templates/motd-default.j2
        dest: /etc/motd
        backup: yes
      become: yes
